#########
# Reuse #
#########
variables:

stages:
  - Quality     # Quality checks, unit tests, lints, etc

###########
# Quality #
###########
.quality:
  stage: Quality
  image: node:10
  before_script:
    - npm install

Lint:
  extends: .quality
  script:
    - npm run lint
