#########
# Reuse #
#########
variables:

stages:
  - Quality     # Quality checks, unit tests, lints, etc
  - Release

image: node:10


###########
# Quality #
###########
Lint:
  stage: Quality
  before_script:
    - npm install
  script:
    - npm run lint

###########
# Release #
###########

pages:
  stage: Release
  only:
  - master
  artifacts:
    paths:
    - public
